kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../../base/ping-cloud/pingaccess

generatorOptions:
  disableNameSuffixHash: false

configMapGenerator:

# Create the config maps that hold the variable for triggering updates of PA servers
- name: pingaccess-last-update-config
  envs:
  - env_vars

- name: pingaccess-environment-variables
  behavior: merge
  envs:
  - ../../env_vars
  - env_vars