kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
# PingCloud common resources
- ${K8S_GIT_URL}/k8s-configs/ping-cloud/${KUSTOMIZE_BASE}/pingcommon?ref=${K8S_GIT_BRANCH}

generatorOptions:
  disableNameSuffixHash: false

configMapGenerator:

# Force all regions to inherit pingcommon-environment-variables merged changes
- name: pingcommon-environment-variables
  behavior: merge
  envs:
  - env_vars