kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- hpa.yaml
- ingress.yaml
- service.yaml
- deployment.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: pingdelegator-environment-variables
  envs:
  - env_vars