kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ${K8S_GIT_URL}/k8s-configs/ping-cloud/${KUSTOMIZE_BASE}/pingfederate?ref=${K8S_GIT_BRANCH}

generatorOptions:
  disableNameSuffixHash: true

patchesJson6902:

# Set a hostname for all the headless services so their endpoint IPs are published to Route53
- target:
    version: v1
    kind: Service
    name: pingfederate-cluster
  patch: |-
    - op: replace
      path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
      value: pingfederate-cluster.${DNS_ZONE}